server:
# The gateway will run on the port 8080
  port: 8080

spring:
  application:
    name: gateway
# An example routing (real routing instances are to be added as the project progresses)
  #cloud:
    #gateway:
      #routes:
        #- id: payment-service-route
        #  uri: lb://payment-service  # Eureka load-balanced URI for payment-service
        #  predicates:
            #- Path=/payment/**

eureka:
  client:
    service-url:
    # URL of the Eureka Server (can be changed in the future)
      defaultZone: http://localhost:8761/eureka/  