spring:
    application:
      name: eureka-server

server:
# The conventional port for Eureka Server
  port: 8761
  
eureka:
    instance:
      hostname: localhost
    client:
    # Eureka client does not register itself to the Eureka server
      register-with-eureka: false
    # Eureka lient does not fetch service registry from Eureka server
      fetch-registry: false
      service-url:
      # The address of the Eureka server
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka